user_counter_homepage:
    path:     /
    defaults: { _controller: UserCounterBundle:Default:index }

user_info:
    path: /info/{userEmail}
    defaults: { _controller: UserCounterBundle:Default:info }
    
user_info_change:
    path: /info/change_info/{userEmail}
    defaults: { _controller: UserCounterBundle:Default:infoChange, userEmail: userEmail }